// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRzNNLpSWWVsRx9WwjJuenQteZDkPZPw',
    appId: '1:824881383524:web:f72d532a6dc94e991e7771',
    messagingSenderId: '824881383524',
    projectId: 'evently-cbe23',
    authDomain: 'evently-cbe23.firebaseapp.com',
    storageBucket: 'evently-cbe23.firebasestorage.app',
    measurementId: 'G-VP5WWN8R0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS53dd6Y85XUJxHCeyIFt6JmoIQhUSXK0',
    appId: '1:824881383524:android:57e0e3c628910b1f1e7771',
    messagingSenderId: '824881383524',
    projectId: 'evently-cbe23',
    storageBucket: 'evently-cbe23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzap31SpMi3YCjEO1C2f4wlZQ3RTFUn0',
    appId: '1:824881383524:ios:fa4cd84b15d9555c1e7771',
    messagingSenderId: '824881383524',
    projectId: 'evently-cbe23',
    storageBucket: 'evently-cbe23.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzap31SpMi3YCjEO1C2f4wlZQ3RTFUn0',
    appId: '1:824881383524:ios:fa4cd84b15d9555c1e7771',
    messagingSenderId: '824881383524',
    projectId: 'evently-cbe23',
    storageBucket: 'evently-cbe23.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVRzNNLpSWWVsRx9WwjJuenQteZDkPZPw',
    appId: '1:824881383524:web:dd8febb77caf09e71e7771',
    messagingSenderId: '824881383524',
    projectId: 'evently-cbe23',
    authDomain: 'evently-cbe23.firebaseapp.com',
    storageBucket: 'evently-cbe23.firebasestorage.app',
    measurementId: 'G-9BHTQ5KW00',
  );
}
